#### This is a sample of 1 row with headers explanation:
##### 1,PAYMENT,1060.31,C429214117,1089.0,28.69,M1591654462,0.0,0.0,0,0

**step** - maps a unit of time in the real world. In this case 1 step is 1 hour of time. Total steps 744 (30 days simulation).

**type** - CASH-IN, CASH-OUT, DEBIT, PAYMENT and TRANSFER.

**amount** -
amount of the transaction in local currency.

**nameOrig** - customer who started the transaction

**oldbalanceOrg** - initial balance before the transaction

**newbalanceOrig** - new balance after the transaction.

**nameDest** - customer who is the recipient of the transaction

**oldbalanceDest** - initial balance recipient before the transaction. Note that there is not information for customers that start with M (Merchants).

**newbalanceDest**- new balance recipient after the transaction. Note that there is not information for customers that start with M (Merchants).

**isFraud** - This is the transactions made by the fraudulent agents inside the simulation. In this specific dataset the fraudulent behavior of the agents aims to profit by taking control or customers accounts and try to empty the funds by transferring to another account and then cashing out of the system.

**isFlaggedFraud** - The business model aims to control massive transfers from one account to another and flags illegal attempts. An illegal attempt in this dataset is an attempt to transfer more than 200.000 in a single transaction.

In [ ]:
import pandas as pd
import numpy as np
data=pd.read_csv("fraud_dataset.csv")
# 计算 1/3 的行数
one_third = len(df) // 3

# 获取前 1/3 的数据
df_first_third = df.iloc[:one_third]

In [ ]:
##### Null data exist

In [ ]:
pd.isnull(data).sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [4]:
data.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [5]:
data.describe()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06
mean,2.433972e+02,1.798619e+05,8.338831e+05,8.551137e+05,1.100702e+06,1.224996e+06,1.290820e-03,2.514687e-06
std,1.423320e+02,6.038582e+05,2.888243e+06,2.924049e+06,3.399180e+06,3.674129e+06,3.590480e-02,1.585775e-03
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.560000e+02,1.338957e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.390000e+02,7.487194e+04,1.420800e+04,0.000000e+00,1.327057e+05,2.146614e+05,0.000000e+00,0.000000e+00
75%,3.350000e+02,2.087215e+05,1.073152e+05,1.442584e+05,9.430367e+05,1.111909e+06,0.000000e+00,0.000000e+00
max,7.430000e+02,9.244552e+07,5.958504e+07,4.958504e+07,3.560159e+08,3.561793e+08,1.000000e+00,1.000000e+00

In [6]:
data.columns

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
       'isFlaggedFraud'],
      dtype='object')

In [7]:
data[data["step"].values==1].shape

(2708, 11)

In [8]:
bigAmountTranscation=data[data["isFlaggedFraud"]==1]
bigAmountTranscation

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
2736446,212,TRANSFER,4953893.08,C728984460,4953893.08,4953893.08,C639921569,0.0,0.0,1,1
3247297,250,TRANSFER,1343002.08,C1100582606,1343002.08,1343002.08,C1147517658,0.0,0.0,1,1
3760288,279,TRANSFER,536624.41,C1035541766,536624.41,536624.41,C1100697970,0.0,0.0,1,1
5563713,387,TRANSFER,4892193.09,C908544136,4892193.09,4892193.09,C891140444,0.0,0.0,1,1
5996407,425,TRANSFER,10000000.00,C689608084,19585040.37,19585040.37,C1392803603,0.0,0.0,1,1
5996409,425,TRANSFER,9585040.37,C452586515,19585040.37,19585040.37,C1109166882,0.0,0.0,1,1
6168499,554,TRANSFER,3576297.10,C193696150,3576297.10,3576297.10,C484597480,0.0,0.0,1,1
6205439,586,TRANSFER,353874.22,C1684585475,353874.22,353874.22,C1770418982,0.0,0.0,1,1
6266413,617,TRANSFER,2542664.27,C786455622,2542664.27,2542664.27,C661958277,0.0,0.0,1,1
6281482,646,TRANSFER,10000000.00,C19004745,10399045.08,10399045.08,C1806199534,0.0,0.0,1,1
6281484,646,TRANSFER,399045.08,C724693370,10399045.08,10399045.08,C1909486199,0.0,0.0,1,1
6296014,671,TRANSFER,3441041.46,C917414431,3441041.46,3441041.46,C1082139865,0.0,0.0,1,1
6351225,702,TRANSFER,3171085.59,C1892216157,3171085.59,3171085.59,C1308068787,0.0,0.0,1,1
6362460,730,TRANSFER,10000000.00,C2140038573,17316255.05,17316255.05,C1395467927,0.0,0.0,1,1
6362462,730,TRANSFER,7316255.05,C1869569059,17316255.05,17316255.05,C1861208726,0.0,0.0,1,1
6362584,741,TRANSFER,5674547.89,C992223106,5674547.89,5674547.89,C1366804249,0.0,0.0,1,1

In [9]:
bigAmountTranscation.count()

step              16
type              16
amount            16
nameOrig          16
oldbalanceOrg     16
newbalanceOrig    16
nameDest          16
oldbalanceDest    16
newbalanceDest    16
isFraud           16
isFlaggedFraud    16
dtype: int64

In [10]:
data[data["isFraud"]==1].count()

step              8213
type              8213
amount            8213
nameOrig          8213
oldbalanceOrg     8213
newbalanceOrig    8213
nameDest          8213
oldbalanceDest    8213
newbalanceDest    8213
isFraud           8213
isFlaggedFraud    8213
dtype: int64

##### Data preprocessing
1. Drop redundant features

In [11]:
# drop "is Flagged Fraud"
data=data.drop(columns="isFlaggedFraud")

In [16]:
import torch
import torch.nn as nn

**2. Embedding**

In [17]:
nameOrig_colunm=data["nameOrig"]
nameDest_colunm=data["nameDest"]
chars=set(''.join(nameOrig_colunm + nameDest_colunm))
char_to_idx={char:idx for idx, char in enumerate(chars)}

def names_to_sequences(names, char_to_idx):
    sequences=[]
    for name in names:
        sequence=[char_to_idx[char] for char in name]
        sequences.append(sequence)
    return sequences
name_Orig_sequences= names_to_sequences(nameOrig_colunm, char_to_idx)
name_Dest_sequences= names_to_sequences(nameDest_colunm, char_to_idx)

max_len1=max(len(seq) for seq in name_Orig_sequences)
max_len2=max(len(seq) for seq in name_Dest_sequences)
# 取两者的最大值作为统一的序列长度
max_len = max(max_len1, max_len2)
name_Orig_padded_sequences=[seq+[0]*(max_len-len(seq)) for seq in name_Orig_sequences]
name_Dest_padded_sequences=[seq+[0]*(max_len-len(seq)) for seq in name_Dest_sequences]
# 计算张量 (要用torch.tensor而不是Tensor!)
name_Orig_padded_sequences=torch.tensor(name_Orig_padded_sequences, dtype=torch.long)
name_Dest_padded_sequences=torch.tensor(name_Dest_padded_sequences, dtype=torch.long)
# define embedding layers
embedding_dim=3
embedding_layer=nn.Embedding(num_embeddings=len(char_to_idx), embedding_dim=embedding_dim)
# embedding vector of account features
name_Orig_embedded= embedding_layer(name_Orig_padded_sequences)
name_Dest_embedded= embedding_layer(name_Dest_padded_sequences)

3, Replace name_Orig and name_Dest feature to embedded ones

In [18]:
data.columns

Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud'],
      dtype='object')

In [19]:
# convert to numpy type
name_Orig_embedded_np=name_Orig_embedded.detach().numpy()
name_Dest_embedded_np=name_Dest_embedded.detach().numpy()
# 保存 Embedding 结果到本地
np.save('name_Orig_embedded.npy', name_Orig_embedded_np)
np.save('name_Dest_embedded.npy', name_Dest_embedded_np)

# 释放缓存
del name_Orig_embedded, name_Dest_embedded, name_Orig_embedded_np, name_Dest_embedded_np
del name_Orig_padded_sequences, name_Dest_padded_sequences
torch.cuda.empty_cache()  # 如果使用 GPU，清理显存

# 加载 Embedding 结果
name_Orig_embedded_np = np.load('name_Orig_embedded.npy')
name_Dest_embedded_np = np.load('name_Dest_embedded.npy')

# replace 
data["nameOrig_embedded"]=list(name_Orig_embedded_np)
data["nameDest_embedded"]=list(name_Dest_embedded_np)
data=data.drop(columns=["nameOrig","nameDest"])
data.head()

,step,type,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,nameOrig_embedded,nameDest_embedded
0,1,PAYMENT,9839.64,170136.0,160296.36,0.0,0.0,0,"[[0.9466233, -0.2885346, 0.13954516], [0.89944...","[[-0.22825971, 1.0308051, -0.73506564], [0.899..."
1,1,PAYMENT,1864.28,21249.0,19384.72,0.0,0.0,0,"[[0.9466233, -0.2885346, 0.13954516], [0.89944...","[[-0.22825971, 1.0308051, -0.73506564], [-0.44..."
2,1,TRANSFER,181.00,181.0,0.00,0.0,0.0,1,"[[0.9466233, -0.2885346, 0.13954516], [0.89944...","[[0.9466233, -0.2885346, 0.13954516], [0.34584..."
3,1,CASH_OUT,181.00,181.0,0.00,21182.0,0.0,1,"[[0.9466233, -0.2885346, 0.13954516], [-1.6434...","[[0.9466233, -0.2885346, 0.13954516], [0.12473..."
4,1,PAYMENT,11668.14,41554.0,29885.86,0.0,0.0,0,"[[0.9466233, -0.2885346, 0.13954516], [-0.4484...","[[-0.22825971, 1.0308051, -0.73506564], [0.899..."

4, one-hot encoding for transaction type

In [20]:
data_onehot=pd.get_dummies(data, columns=["type"])
data_onehot.head()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,nameOrig_embedded,nameDest_embedded,type_CASH_IN,type_CASH_OUT,type_DEBIT,type_PAYMENT,type_TRANSFER
0,1,9839.64,170136.0,160296.36,0.0,0.0,0,"[[0.9466233, -0.2885346, 0.13954516], [0.89944...","[[-0.22825971, 1.0308051, -0.73506564], [0.899...",False,False,False,True,False
1,1,1864.28,21249.0,19384.72,0.0,0.0,0,"[[0.9466233, -0.2885346, 0.13954516], [0.89944...","[[-0.22825971, 1.0308051, -0.73506564], [-0.44...",False,False,False,True,False
2,1,181.00,181.0,0.00,0.0,0.0,1,"[[0.9466233, -0.2885346, 0.13954516], [0.89944...","[[0.9466233, -0.2885346, 0.13954516], [0.34584...",False,False,False,False,True
3,1,181.00,181.0,0.00,21182.0,0.0,1,"[[0.9466233, -0.2885346, 0.13954516], [-1.6434...","[[0.9466233, -0.2885346, 0.13954516], [0.12473...",False,True,False,False,False
4,1,11668.14,41554.0,29885.86,0.0,0.0,0,"[[0.9466233, -0.2885346, 0.13954516], [-0.4484...","[[-0.22825971, 1.0308051, -0.73506564], [0.899...",False,False,False,True,False

##### Split data into training , validation, testing dataset  
flatten the embedding feature in order to fit further processing for models  
Resample the training set: undersample (reduce the majority negetive samples), oversample(increase the minority positive samples)  
Keep the validation and testing dataset as original to simulate real situation of transactions.

In [21]:
from sklearn.model_selection import train_test_split
# flatten the embedding features
data_onehot['nameOrig_embedded'] = data_onehot['nameOrig_embedded'].apply(lambda x: np.array(x).flatten())
data_onehot['nameDest_embedded'] = data_onehot['nameDest_embedded'].apply(lambda x: np.array(x).flatten())
# 将展平后的嵌入向量与其他特征拼接
scalar_features = data_onehot.drop(columns=['nameOrig_embedded', 'nameDest_embedded', 'isFraud'])
embeddings_orig = np.array(data_onehot['nameOrig_embedded'].tolist())
embeddings_dest = np.array(data_onehot['nameDest_embedded'].tolist())
# 拼接所有特征
all_features = np.hstack([scalar_features, embeddings_orig, embeddings_dest])

# 将拼接后的特征重新转换为 DataFrame
feature_columns = scalar_features.columns.tolist() + \
                 [f'orig_embed_{i}' for i in range(embeddings_orig.shape[1])] + \
                 [f'dest_embed_{i}' for i in range(embeddings_dest.shape[1])]
data_flattened = pd.DataFrame(all_features, columns=feature_columns)
data_flattened['isFraud'] = data_onehot['isFraud']  # 添加目标列

In [30]:
data_flattened.head()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,type_CASH_IN,type_CASH_OUT,type_DEBIT,type_PAYMENT,...,dest_embed_24,dest_embed_25,dest_embed_26,dest_embed_27,dest_embed_28,dest_embed_29,dest_embed_30,dest_embed_31,dest_embed_32,isFraud
0,1,9839.64,170136.0,160296.36,0.0,0.0,False,False,False,True,...,0.899446,1.424368,-1.152897,0.345847,0.21385,0.266833,0.345847,0.21385,0.266833,0
1,1,1864.28,21249.0,19384.72,0.0,0.0,False,False,False,True,...,-0.448453,-0.542259,0.609989,-0.448453,-0.542259,0.609989,0.345847,0.21385,0.266833,0
2,1,181.0,181.0,0.0,0.0,0.0,False,False,False,False,...,-0.328998,-0.679764,0.519706,0.345847,0.21385,0.266833,0.393168,0.32864,0.133577,1
3,1,181.0,181.0,0.0,21182.0,0.0,False,True,False,False,...,-0.073491,-0.697079,-0.781869,0.393168,0.32864,0.133577,0.393168,0.32864,0.133577,1
4,1,11668.14,41554.0,29885.86,0.0,0.0,False,False,False,True,...,0.393168,0.32864,0.133577,-0.073491,-0.697079,-0.781869,0.124738,-0.518232,1.624826,0

In [22]:
# 1. 分割正常交易数据和欺诈数据
normal_data = data_flattened[data_flattened["isFraud"] == 0]
fraud_data = data_flattened[data_flattened["isFraud"] == 1]

# 2. 分别划分正常数据和欺诈数据
# 正常数据
normal_train, normal_temp = train_test_split(normal_data, test_size=0.4, random_state=42)  # 60% 训练集
normal_val, normal_test = train_test_split(normal_temp, test_size=0.5, random_state=42)    # 20% 验证集，20% 测试集

# 欺诈数据
fraud_train, fraud_temp = train_test_split(fraud_data, test_size=0.4, random_state=42)  # 60% 训练集
fraud_val, fraud_test = train_test_split(fraud_temp, test_size=0.5, random_state=42)    # 20% 验证集，20% 测试集
# concat the validation and test data
val_data = pd.concat([normal_val, fraud_val])
test_data = pd.concat([normal_test, fraud_test])
# shuffle the order of data
val_data = val_data.sample(frac=1, random_state=42).reset_index(drop=True)
test_data = test_data.sample(frac=1, random_state=42).reset_index(drop=True)
# split the target data and validation data of validation and test 
X_val = val_data.drop(columns=["isFraud"])
y_val = val_data["isFraud"]
X_test = test_data.drop(columns=["isFraud"])
y_test = test_data["isFraud"]

#### Resampling and Undersampling for training data

##### GANs simulates minority Fraud_data

In [23]:

print(f"The numbers of normal transactions: {len(normal_train)}")
print(f"The numbers of normal transactions: {len(fraud_train)}")

The numbers of normal transactions: 3812644
The numbers of normal transactions: 4927

In [24]:
# only use feature values of fraud transactions trainning set.
# 提取特征数据（去掉目标值列）
X_fraud = fraud_train.drop(columns="isFraud").values  # 特征数据
y_fraud = fraud_train["isFraud"].values   # 目标值列

In [45]:
X_fraud = fraud_train.drop(columns="isFraud").apply(pd.to_numeric, errors='coerce').astype(np.float32).values

In [52]:
# print(X_fraud.dtype)
print(fraud_train.dtypes)
print(X_fraud.dtype)

step              object
amount            object
oldbalanceOrg     object
newbalanceOrig    object
oldbalanceDest    object
                   ...
dest_embed_29     object
dest_embed_30     object
dest_embed_31     object
dest_embed_32     object
isFraud            int64
Length: 78, dtype: object
float32

In [25]:
fraud_data.head()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,type_CASH_IN,type_CASH_OUT,type_DEBIT,type_PAYMENT,...,dest_embed_24,dest_embed_25,dest_embed_26,dest_embed_27,dest_embed_28,dest_embed_29,dest_embed_30,dest_embed_31,dest_embed_32,isFraud
2,1,181.0,181.0,0.0,0.0,0.0,False,False,False,False,...,-0.328998,-0.679764,0.519706,0.345847,0.21385,0.266833,0.393168,0.32864,0.133577,1
3,1,181.0,181.0,0.0,21182.0,0.0,False,True,False,False,...,-0.073491,-0.697079,-0.781869,0.393168,0.32864,0.133577,0.393168,0.32864,0.133577,1
251,1,2806.0,2806.0,0.0,0.0,0.0,False,False,False,False,...,0.393168,0.32864,0.133577,-1.643453,0.176569,0.671764,0.393168,0.32864,0.133577,1
252,1,2806.0,2806.0,0.0,26202.0,0.0,False,True,False,False,...,0.393168,0.32864,0.133577,0.124738,-0.518232,1.624826,0.242879,-0.445476,0.833478,1
680,1,20128.0,20128.0,0.0,0.0,0.0,False,False,False,False,...,-0.073491,-0.697079,-0.781869,-0.256324,0.394816,0.712671,0.899446,1.424368,-1.152897,1

In [53]:
import torch
import torch.nn as nn
import torch.optim as optim

# 定义生成器
class Generator(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(Generator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 256),
            nn.ReLU(),
            nn.Linear(256, output_dim),
            nn.Tanh()
        )

    def forward(self, x):
        return self.model(x)

# 定义判别器
class Discriminator(nn.Module):
    def __init__(self, input_dim):
        super(Discriminator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, 128),
            nn.LeakyReLU(0.2),
            nn.Linear(128, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)
# 初始化模型
input_dim = X_fraud.shape[1]  # feature columns
output_dim = input_dim
generator = Generator(input_dim, output_dim)
discriminator = Discriminator(input_dim)

# 定义优化器和损失函数
lr = 0.0002
criterion = nn.BCELoss()
optimizer_G = optim.Adam(generator.parameters(), lr=lr)
optimizer_D = optim.Adam(discriminator.parameters(), lr=lr)

In [56]:
print(X_fraud.dtype)  # 检查数据类型
print(type(X_fraud))
print(type(X_fraud[0]))  # 检查第一行的数据类型

float32
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [64]:
# 训练GAN
epochs = 10
batch_size = 64
for epoch in range(epochs):
    for i in range(0, len(X_fraud), batch_size):
        # 真实数据（仅特征列）
        real_data = torch.tensor(X_fraud[i:i+batch_size], dtype=torch.float32)
        real_labels = torch.ones((real_data.size(0), 1))

        # 生成假数据
        noise = torch.randn((real_data.size(0), input_dim))
        fake_data = generator(noise)
        fake_labels = torch.zeros((real_data.size(0), 1))

        # 训练判别器
        discriminator.zero_grad()
        real_loss = criterion(discriminator(real_data), real_labels)
        fake_loss = criterion(discriminator(fake_data.detach()), fake_labels)
        d_loss = real_loss + fake_loss
        d_loss.backward()
        optimizer_D.step()

        # 训练生成器
        generator.zero_grad()
        g_loss = criterion(discriminator(fake_data), real_labels)
        g_loss.backward()
        optimizer_G.step()

    if epoch % 1 == 0:
        print(f"Epoch {epoch}, D Loss: {d_loss.item()}, G Loss: {g_loss.item()}")

# 生成欺诈样本
num_fake_samples = (len(normal_train)+len(fraud_train))//2 - len(fraud_train)# 生成足够的样本以平衡数据
noise = torch.randn((num_fake_samples, input_dim))
generated_fraud_data = generator(noise).detach().numpy()
generated_fraud_data = pd.DataFrame(generated_fraud_data, columns=fraud_data.drop(columns="isFraud").columns)
# generated_fraud_data['isFraud'] = 1  # 标记为欺诈

Epoch 0, D Loss: 0.0007148885051719844, G Loss: 7.309364318847656
Epoch 1, D Loss: 0.0006175756570883095, G Loss: 7.429353713989258
Epoch 2, D Loss: 0.0003842861042357981, G Loss: 7.88485860824585
Epoch 3, D Loss: 0.0004901497159153223, G Loss: 7.662798881530762
Epoch 4, D Loss: 0.0004445286758709699, G Loss: 7.757200241088867
Epoch 5, D Loss: 0.00046567837125621736, G Loss: 7.697729587554932
Epoch 6, D Loss: 0.00038060909719206393, G Loss: 7.897017478942871
Epoch 7, D Loss: 0.0003735728678293526, G Loss: 7.919463634490967
Epoch 8, D Loss: 0.0003702890535350889, G Loss: 7.939112663269043
Epoch 9, D Loss: 0.00034269163734279573, G Loss: 8.013279914855957

##### evaluate the similarity of the generated data and true data

In [70]:
generated_fraud_data["label"]=0 #add the label the generated data
origin_fraud_data=fraud_data.drop(columns="isFraud")
origin_fraud_data["label"]=1
# calculate the batch 
num_real_samples = len(fraud_data)  # 真实数据的样本量
num_generated_samples = len(generated_fraud_data)  # 生成数据的样本量
num_batches = num_generated_samples // num_real_samples  # 计算批次数量
# split generated data into groups
generated_batches = np.array_split(generated_fraud_data, num_batches)

print(len(generated_batches))

D:\Python312\Lib\site-packages\numpy\core\fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

231

In [72]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,roc_auc_score,classification_report
accuracy_scores = []
auc_scores = []
for i,batch in enumerate(generated_batches):
    if i % 10 == 0:
        combined_data=pd.concat([batch, origin_fraud_data],axis=0) #combine real and fake data
        # 打乱数据
        combined_data = combined_data.sample(frac=1, random_state=42).reset_index(drop=True)
        # split target and feature
        X = combined_data.drop(columns=['label'])  # feature
        y = combined_data['label']  # target
        X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.2, random_state=42)
        # 训练随机森林分类器
        rf = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
        rf.fit(X_train, y_train)
        # 在测试集上评估
        y_test_pred = rf.predict(X_test)
        test_accuracy = accuracy_score(y_test, y_test_pred)
        test_auc = roc_auc_score(y_test, rf.predict_proba(X_test)[:, 1])
        # 保存结果
        accuracy_scores.append(test_accuracy)
        auc_scores.append(test_auc)
    
        print(f"Batch {i+1} - Test Accuracy: {test_accuracy:.4f}, Test AUC-ROC: {test_auc:.4f}")

Batch 1 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 11 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 21 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 31 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 41 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 51 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 61 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 71 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 81 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 91 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 101 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 111 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 121 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 131 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 141 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 151 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 161 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 171 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 181 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 191 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 201 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 211 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 221 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000
Batch 231 - Test Accuracy: 1.0000, Test AUC-ROC: 1.0000

In [67]:
pd.isnull(combined_data).sum()

step                 0
amount               0
oldbalanceOrg        0
newbalanceOrig       0
oldbalanceDest       0
                  ...
dest_embed_30        0
dest_embed_31        0
dest_embed_32        0
label             8213
isFraud           8242
Length: 79, dtype: int64

In [73]:
# 4. 计算平均结果
mean_accuracy = np.mean(accuracy_scores)
mean_auc = np.mean(auc_scores)

print("\nFinal Results:")
print(f"Mean Accuracy: {mean_accuracy:.4f}")
print(f"Mean AUC-ROC: {mean_auc:.4f}")

Final Results:
Mean Accuracy: 1.0000
Mean AUC-ROC: 1.0000

##### K-means to undersample

##### 运行到这里就可以了

In [ ]:
from sklearn.cluster import KMeans

# 对正常交易样本聚类
kmeans = KMeans(n_clusters=1000, random_state=42)  # 假设聚类为1000类
normal_data_clusters = kmeans.fit_predict(normal_data.iloc[:, :-1])

# 从每个聚类中抽取样本
reduced_normal_data = pd.DataFrame()
for cluster in range(1000):
    cluster_samples = normal_data[normal_data_clusters == cluster]
    reduced_normal_data = pd.concat([reduced_normal_data, cluster_samples.sample(n=10)])  # 每类抽取10个样本

print(f"缩减后的正常交易样本数: {len(reduced_normal_data)}")

In [ ]:
# 合并数据集
balanced_data = pd.concat([reduced_normal_data, fraud_data, generated_fraud_data], ignore_index=True)

# 打乱数据
balanced_data = balanced_data.sample(frac=1).reset_index(drop=True)

# 保存数据
balanced_data.to_csv('balanced_data.csv', index=False)

##### varify the data

In [ ]:
print(balanced_data['isFraud'].value_counts())

# 训练模型（示例：随机森林）
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X = balanced_data.iloc[:, :-1]
y = balanced_data['isFraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

##### Random Forest
fit data to model to get F1score of validation set,then draw the ROC curve to evaluate model on the training set.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
# initiate model
rf_model=RandomForestClassifier(n_estimators=100,random_state=44)
rf_model.fit(X_train,y_train)

In [ ]:
from sklearn.metrics import precision_recall_curve, roc_auc_score,roc_curve,auc
import numpy as np
import matplotlib.pyplot as plt
y_val_pro= rf_model.predict_proba(X_val)[:,1] #positive result

# prescision_recall_curve
precisions,recalls,thresholds=precision_recall_curve(y_val,y_val_pro)

roc_auc=roc_auc_score(y_val,y_val_pro)
fpr, tpr, thresholds = roc_curve(y_val,y_val_pro)

print(f"AUC: {roc_auc}")

##### show the figure of ROC
indicate the performance of model in training and validation set

In [ ]:
plt.figure(figsize=(10,8))
plt.plot(fpr, tpr, color='blue', lw=2, label=f"ROC curve (AUC = {roc_auc:.2f})")
plt.plot([0,1],[0,1],color="red", linestyle='--',lw=1.5)
plt.xlim([0,1])
plt.ylim([0,1])
plt.xlabel("FPR",fontsize=13)
plt.ylabel("TPR",fontsize=13)
plt.title("ROC-curve",fontsize=15)
plt.legend(loc="lower right")
plt.grid(linestyle="-.",alpha=0.5)
plt.show()